### ISSUE TITLE
nginx conf in readme.rst and config.rst

### ISSUE THREAD

**Issue by bitnik** [nginx-shib/nginx-http-shibboleth#30]
Hi, first I must say I am really not competent at nginx. While reading README.rst and CONFIG.rst files, I realized a difference in nginx configurations.

In README.rst in `location /secure` first `shib_request` and `shib_request_use_headers` are called and then `more_clear_input_headers` is called. But in CONFIG.rst it is vice versa. Does this mean the order there is not important at all? For me the one in CONFIG.rst looks correct.

Thanks a lot!

**Comment by davidjb** [comment]
For these types of directives, the ordering doesn't matter -- they're all applied to the `location` block.  For some other types of nginx directives (such as [`allow`](http://nginx.org/en/docs/http/ngx_http_access_module.html#allow) and `deny` etc; not specifically related to this project), order will matter.

In terms of consistency in the docs for this project, I recall the reason for some of the docs (eg https://github.com/nginx-shib/nginx-http-shibboleth#configuration) being in a different order was to highlight/separate out certain directives.  That said, if you'd like you could make a pull request with a note about ordering or otherwise normalise the different configs to have same order.  Up to you if you're keen, no worries otherwise!

**Comment by bitnik** [comment]
Thanks a lot for the explanation. If order is not important, I think there is no need to change the documentation.
