### ISSUE TITLE
Testing the SAML functionality with shibboleth and NGINX integration

### ISSUE THREAD

**Issue by jkmuthusamy** [nginx-shib/nginx-http-shibboleth#37]
Hi,
We integrated Shibboleth module in our project with nginx. We are testing the integration with below URL
https://hostname:8443/Shibboleth.sso/

Could you please confirm this is the right way of testing?

I'm able to run shibd, supervisord and nginx plus instances.
Now i'm trying to test the  working of Shibboleth SAML integration with the application running in nginx.

When i try to hit https://hostname:8443/Shibboleth.sso/Status , i'm getting the below output

![image](https://user-images.githubusercontent.com/54150050/63929193-a54cd500-ca6e-11e9-9ed3-c20eadaf8e7d.png)

 
but when i hit https://hostname:8443/Shibboleth.sso/Status/  (added'/' after "Status", like /Status/), i'm getting the below output

![image](https://user-images.githubusercontent.com/54150050/63929304-d2998300-ca6e-11e9-9b73-1168c0f01df4.png)

In our application we need to interact with PingFederate(Idp) from shibboleth . Want to know do we need to generate any metadata xml from shibboleth?
We have metadata xml from our idp which we gave with <MetadataProvider /> tag

Idp Entity Id we gave as  

```
<SSO entityID="https://my-idp-url/shibboleth">
              SAML2
</SSO> 
```

Below is the shibboleth2.xml configs:

Shibboleth2.xml:

<SPConfig xmlns="urn:mace:shibboleth:3.0:native:sp:config"
    xmlns:conf="urn:mace:shibboleth:3.0:native:sp:config"
    clockSkew="180">

    <OutOfProcess tranLogFormat="%u|%s|%IDP|%i|%ac|%t|%attr|%n|%b|%E|%S|%SS|%L|%UA|%a" />
    <RequestMapper type="XML">
    <RequestMap>
        <Host name="https://d1l00313g.dc01.its.hpecorp.net"
              authType="shibboleth"
              requireSession="true"
              redirectToSSL="443">
            <Path name="/secure" />
            <Path name="/secure2/shibboleth" />

        </Host>

    </RequestMap>
   </RequestMapper>
    

    
    <ApplicationDefaults entityID="https://d1l00313g.dc01.its.hpecorp.net/shibboleth"
        REMOTE_USER="eppn subject-id pairwise-id persistent-id"
        cipherSuites="DEFAULT:!EXP:!LOW:!aNULL:!eNULL:!DES:!IDEA:!SEED:!RC4:!3DES:!kRSA:!SSLv2:!SSLv3:!TLSv1:!TLSv1.1">

        
        <Sessions lifetime="28800" timeout="3600" relayState="ss:mem"
                  checkAddress="false" handlerSSL="true" cookieProps="https">

            
            <SSO entityID="https://login-itg.ext.hpe.com/shibboleth">
              SAML2
            </SSO>

            
            <Logout>SAML2 Local</Logout>

            
            <LogoutInitiator type="Admin" Location="/Logout/Admin" acl="127.0.0.1 ::1" />

            
            <Handler type="MetadataGenerator" Location="/Metadata" signing="false"/>

            
            <Handler type="Status" Location="/Status" acl="127.0.0.1 ::1"/>

            
            <Handler type="Session" Location="/Session" showAttributeValues="false"/>

            
            <Handler type="DiscoveryFeed" Location="/DiscoFeed"/>
        </Sessions>

        
        <Errors supportContact="root@localhost"
            helpLocation="/about.html"
            styleSheet="/shibboleth-sp/main.css"/>

        

        <MetadataProvider type="XML" validate="true" path="itg_sp_nginx_metadata_uid.xml"/>

        
        

        
        

        
        <AttributeExtractor type="XML" validate="true" reloadChanges="false" path="attribute-map.xml"/>

        
        <AttributeFilter type="XML" validate="true" path="attribute-policy.xml"/>

        
        <CredentialResolver type="File" key="/opt/serviceproxy/conf/ssl/svcproxy-dev.key" certificate="/opt/serviceproxy/conf/ssl/svcproxy-dev.pem"/>

    </ApplicationDefaults>

    
    <SecurityPolicyProvider type="XML" validate="true" path="security-policy.xml"/>

    
    <ProtocolProvider type="XML" validate="true" reloadChanges="false" path="protocols.xml"/>

</SPConfig>

Could any one please provide how i can test the working of shibboleth and SAML functionality ?

**Comment by davidjb** [comment]
The output you've got coming from https://hostname:8443/Shibboleth.sso/Status and https://hostname:8443/Shibboleth.sso/Status/ are right -- these are standard responses returned by `shibresponder` so that's set up okay.  For testing authorisation, the simplest option is to set up a quick backend application like Bottle -- see https://github.com/nginx-shib/nginx-http-shibboleth/wiki/bottle -- and test attributes and an auth cycle complete correctly.

As for integrating with other software or configuration of Shibboleth, this issue tracker is just for reporting issues with the nginx integration.  You can direct support requests to the Shibboleth Users mailing list (https://www.shibboleth.net/community/lists/) -- they can assist you with specific config or application issues.  Otherwise, speak with your software vendor about what needs to be configured and where for SAML etc.

PR and contributions to the [wiki](https://github.com/nginx-shib/nginx-http-shibboleth/wiki) are welcome if you can share your configuration.
